name: Set up Gradle build environment
description: Prepares environment for building with JDK and Gradle
inputs:
  add-job-summary:
    description: 'Whether to add a job summary (always, never, on-failure).'
    required: false
    default: 'always'
  write-cache:
    description: 'Whether to write to the cache (true/false).'
    required: false
    default: 'false'
  disable-cache:
    description: 'Whether to disable the cache (true/false).'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Copy CI gradle.properties
      shell: bash
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - name: Set up JDK
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Set up Gradle without cache
      uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5.0.1
      with:
        cache-disabled: ${{ inputs.disable-cache }}
        add-job-summary: ${{ inputs.add-job-summary }}
        cache-read-only: ${{ inputs.write-cache == 'false' }}
