/* Generated By:JJTree&JavaCC: Do not edit this line. AddressListParserConstants.java */
/****************************************************************
 * Licensed to the Apache Software Foundation (ASF) under one   *
 * or more contributor license agreements.  See the NOTICE file *
 * distributed with this work for additional information        *
 * regarding copyright ownership.  The ASF licenses this file   *
 * to you under the Apache License, Version 2.0 (the            *
 * "License"); you may not use this file except in compliance   *
 * with the License.  You may obtain a copy of the License at   *
 *                                                              *
 *   http://www.apache.org/licenses/LICENSE-2.0                 *
 *                                                              *
 * Unless required by applicable law or agreed to in writing,   *
 * software distributed under the License is distributed on an  *
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY       *
 * KIND, either express or implied.  See the License for the    *
 * specific language governing permissions and limitations      *
 * under the License.                                           *
 ****************************************************************/
package org.apache.james.mime4j.field.address.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AddressListParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WS = 10;
  /** RegularExpression Id. */
  int ALPHA = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;
  /** RegularExpression Id. */
  int ATEXT = 13;
  /** RegularExpression Id. */
  int DOTATOM = 14;
  /** RegularExpression Id. */
  int DOMAINLITERAL = 18;
  /** RegularExpression Id. */
  int COMMENT = 20;
  /** RegularExpression Id. */
  int QUOTEDSTRING = 31;
  /** RegularExpression Id. */
  int QUOTEDPAIR = 32;
  /** RegularExpression Id. */
  int ANY = 33;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int INDOMAINLITERAL = 1;
  /** Lexical state. */
  int INCOMMENT = 2;
  /** Lexical state. */
  int NESTED_COMMENT = 3;
  /** Lexical state. */
  int INQUOTEDSTRING = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\n\"",
    "\",\"",
    "\":\"",
    "\";\"",
    "\"<\"",
    "\">\"",
    "\"@\"",
    "\".\"",
    "<WS>",
    "<ALPHA>",
    "<DIGIT>",
    "<ATEXT>",
    "<DOTATOM>",
    "\"[\"",
    "<token of kind 16>",
    "<token of kind 17>",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "<token of kind 21>",
    "\"(\"",
    "<token of kind 23>",
    "<token of kind 24>",
    "\"(\"",
    "\")\"",
    "<token of kind 27>",
    "\"\\\"\"",
    "<token of kind 29>",
    "<token of kind 30>",
    "\"\\\"\"",
    "<QUOTEDPAIR>",
    "<ANY>",
  };

}
