/* Generated By:JavaCC: Do not edit this line. AddressListParserVisitor.java Version 5.0 */
package org.apache.james.mime4j.field.address.parser;

public interface AddressListParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTaddress_list node, Object data);
  public Object visit(ASTaddress node, Object data);
  public Object visit(ASTmailbox node, Object data);
  public Object visit(ASTname_addr node, Object data);
  public Object visit(ASTgroup_body node, Object data);
  public Object visit(ASTangle_addr node, Object data);
  public Object visit(ASTroute node, Object data);
  public Object visit(ASTphrase node, Object data);
  public Object visit(ASTaddr_spec node, Object data);
  public Object visit(ASTlocal_part node, Object data);
  public Object visit(ASTdomain node, Object data);
}
/* JavaCC - OriginalChecksum=f57edd9a1eb17afa5907a87b3c51e284 (do not edit this line) */
