/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.fsck.k9;

public final class R {
    public static final class array {
        public static final int account_settings_check_frequency_entries=0x7f050000;
        public static final int account_settings_check_frequency_values=0x7f050001;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int folder_message_list_child_background=0x7f070000;
    }
    public static final class dimen {
        public static final int button_minWidth=0x7f080000;
    }
    public static final class drawable {
        public static final int appointment_indicator_leftside_1=0x7f020000;
        public static final int appointment_indicator_leftside_10=0x7f020001;
        public static final int appointment_indicator_leftside_11=0x7f020002;
        public static final int appointment_indicator_leftside_12=0x7f020003;
        public static final int appointment_indicator_leftside_13=0x7f020004;
        public static final int appointment_indicator_leftside_14=0x7f020005;
        public static final int appointment_indicator_leftside_15=0x7f020006;
        public static final int appointment_indicator_leftside_16=0x7f020007;
        public static final int appointment_indicator_leftside_17=0x7f020008;
        public static final int appointment_indicator_leftside_18=0x7f020009;
        public static final int appointment_indicator_leftside_19=0x7f02000a;
        public static final int appointment_indicator_leftside_2=0x7f02000b;
        public static final int appointment_indicator_leftside_20=0x7f02000c;
        public static final int appointment_indicator_leftside_21=0x7f02000d;
        public static final int appointment_indicator_leftside_3=0x7f02000e;
        public static final int appointment_indicator_leftside_4=0x7f02000f;
        public static final int appointment_indicator_leftside_5=0x7f020010;
        public static final int appointment_indicator_leftside_6=0x7f020011;
        public static final int appointment_indicator_leftside_7=0x7f020012;
        public static final int appointment_indicator_leftside_8=0x7f020013;
        public static final int appointment_indicator_leftside_9=0x7f020014;
        public static final int attached_image_placeholder=0x7f020015;
        public static final int bottombar_565=0x7f020016;
        public static final int btn_dialog=0x7f020017;
        public static final int btn_dialog_disable=0x7f020018;
        public static final int btn_dialog_disable_focused=0x7f020019;
        public static final int btn_dialog_normal=0x7f02001a;
        public static final int btn_dialog_pressed=0x7f02001b;
        public static final int btn_dialog_selected=0x7f02001c;
        public static final int button_indicator_next=0x7f02001d;
        public static final int divider_horizontal_email=0x7f02001e;
        public static final int email_quoted_bar=0x7f02001f;
        public static final int expander_ic_folder=0x7f020020;
        public static final int expander_ic_folder_maximized=0x7f020021;
        public static final int expander_ic_folder_minimized=0x7f020022;
        public static final int folder_message_list_child_background=0x7f020023;
        public static final int ic_delete=0x7f020024;
        public static final int ic_email_attachment=0x7f020025;
        public static final int ic_email_attachment_small=0x7f020026;
        public static final int ic_email_caret_double_light=0x7f020027;
        public static final int ic_email_caret_single_light=0x7f020028;
        public static final int ic_email_thread_open_bottom_default=0x7f020029;
        public static final int ic_email_thread_open_top_default=0x7f02002a;
        public static final int ic_menu_account_list=0x7f02002b;
        public static final int ic_menu_add=0x7f02002c;
        public static final int ic_menu_archive=0x7f02002d;
        public static final int ic_menu_attachment=0x7f02002e;
        public static final int ic_menu_cc=0x7f02002f;
        public static final int ic_menu_close_clear_cancel=0x7f020030;
        public static final int ic_menu_compose=0x7f020031;
        public static final int ic_menu_delete=0x7f020032;
        public static final int ic_menu_edit=0x7f020033;
        public static final int ic_menu_forward_mail=0x7f020034;
        public static final int ic_menu_inbox=0x7f020035;
        public static final int ic_menu_mark=0x7f020036;
        public static final int ic_menu_navigate=0x7f020037;
        public static final int ic_menu_preferences=0x7f020038;
        public static final int ic_menu_refresh=0x7f020039;
        public static final int ic_menu_reply=0x7f02003a;
        public static final int ic_menu_reply_all=0x7f02003b;
        public static final int ic_menu_save_draft=0x7f02003c;
        public static final int ic_menu_search=0x7f02003d;
        public static final int ic_menu_send=0x7f02003e;
        public static final int ic_mms_attachment_small=0x7f02003f;
        public static final int icon=0x7f020040;
        public static final int stat_notify_email_generic=0x7f020041;
        public static final int text_box=0x7f020042;
        public static final int text_box_light=0x7f020043;
    }
    public static final class id {
        public static final int account_always_bcc=0x7f0a000b;
        public static final int account_check_frequency=0x7f0a0018;
        public static final int account_default=0x7f0a0005;
        public static final int account_delete_policy=0x7f0a0013;
        public static final int account_delete_policy_label=0x7f0a0012;
        public static final int account_description=0x7f0a0016;
        public static final int account_email=0x7f0a0002;
        public static final int account_name=0x7f0a000a;
        public static final int account_notify=0x7f0a0019;
        public static final int account_password=0x7f0a0003;
        public static final int account_port=0x7f0a0010;
        public static final int account_require_login=0x7f0a001a;
        public static final int account_require_login_settings=0x7f0a001b;
        public static final int account_security_type=0x7f0a0011;
        public static final int account_server=0x7f0a000f;
        public static final int account_server_label=0x7f0a000e;
        public static final int account_settings=0x7f0a004e;
        public static final int account_signature=0x7f0a000c;
        public static final int account_username=0x7f0a000d;
        public static final int accounts=0x7f0a004d;
        public static final int add_attachment=0x7f0a0053;
        public static final int add_cc_bcc=0x7f0a004f;
        public static final int add_new_account=0x7f0a001d;
        public static final int attachment=0x7f0a003d;
        public static final int attachment_delete=0x7f0a0033;
        public static final int attachment_icon=0x7f0a0039;
        public static final int attachment_info=0x7f0a003a;
        public static final int attachment_name=0x7f0a0034;
        public static final int attachments=0x7f0a002e;
        public static final int bcc=0x7f0a002d;
        public static final int cancel=0x7f0a0009;
        public static final int cc=0x7f0a002c;
        public static final int check_mail=0x7f0a0047;
        public static final int chip=0x7f0a0024;
        public static final int compose=0x7f0a0048;
        public static final int date=0x7f0a0027;
        public static final int debug_logging=0x7f0a0022;
        public static final int delete=0x7f0a0038;
        public static final int delete_account=0x7f0a0046;
        public static final int description=0x7f0a001e;
        public static final int discard=0x7f0a0052;
        public static final int done=0x7f0a0017;
        public static final int download=0x7f0a003b;
        public static final int dump_settings=0x7f0a0049;
        public static final int edit_account=0x7f0a0045;
        public static final int email=0x7f0a001f;
        public static final int empty=0x7f0a001c;
        public static final int folder_name=0x7f0a0029;
        public static final int folder_status=0x7f0a002a;
        public static final int forward=0x7f0a004a;
        public static final int from=0x7f0a0026;
        public static final int imap=0x7f0a0001;
        public static final int imap_path_prefix=0x7f0a0016;
        public static final int imap_path_prefix_section=0x7f0a0015;
        public static final int main_text=0x7f0a002a;
        public static final int manual_setup=0x7f0a0007;
        public static final int mark_as_read=0x7f0a004d;
        public static final int mark_as_unread=0x7f0a0056;
        public static final int message=0x7f0a0008;
        public static final int message_content=0x7f0a0031;
        public static final int new_message_count=0x7f0a0022;
        public static final int next=0x7f0a0005;
        public static final int open=0x7f0a0046;
        public static final int pop=0x7f0a0000;
        public static final int previous=0x7f0a0035;
        public static final int progress=0x7f0a0008;
        public static final int quoted_text=0x7f0a0032;
        public static final int quoted_text_bar=0x7f0a0030;
        public static final int quoted_text_delete=0x7f0a0031;
        public static final int refresh=0x7f0a004c;
        public static final int reply=0x7f0a0036;
        public static final int reply_all=0x7f0a0037;
        public static final int save=0x7f0a0051;
        public static final int send=0x7f0a0050;
        public static final int sensitive_logging=0x7f0a0023;
        public static final int show_pictures=0x7f0a0041;
        public static final int show_pictures_section=0x7f0a0040;
        public static final int subject=0x7f0a0025;
        public static final int text1=0x7f0a0042;
        public static final int text2=0x7f0a0043;
        public static final int to=0x7f0a002b;
        public static final int to_container=0x7f0a003e;
        public static final int to_label=0x7f0a003f;
        public static final int version=0x7f0a0021;
        public static final int view=0x7f0a003c;
    }
    public static final class layout {
        public static final int account_setup_account_type=0x7f030000;
        public static final int account_setup_basics=0x7f030001;
        public static final int account_setup_check_settings=0x7f030002;
        public static final int account_setup_composition=0x7f030003;
        public static final int account_setup_incoming=0x7f030004;
        public static final int account_setup_names=0x7f030005;
        public static final int account_setup_options=0x7f030006;
        public static final int account_setup_outgoing=0x7f030007;
        public static final int accounts=0x7f030008;
        public static final int accounts_item=0x7f030009;
        public static final int debug=0x7f03000a;
        public static final int folder_message_list_child=0x7f03000b;
        public static final int folder_message_list_child_footer=0x7f03000c;
        public static final int folder_message_list_group=0x7f03000d;
        public static final int message_compose=0x7f03000e;
        public static final int message_compose_attachment=0x7f03000f;
        public static final int message_view=0x7f030010;
        public static final int message_view_attachment=0x7f030011;
        public static final int message_view_header=0x7f030012;
        public static final int recipient_dropdown_item=0x7f030013;
    }
    public static final class menu {
        public static final int accounts_context=0x7f090000;
        public static final int accounts_option=0x7f090001;
        public static final int debug_option=0x7f090002;
        public static final int folder_message_list_context=0x7f090003;
        public static final int folder_message_list_option=0x7f090004;
        public static final int message_compose_option=0x7f090005;
        public static final int message_view_option=0x7f090006;
    }
    public static final class string {
        public static final int account_delete_dlg_instructions_fmt=0x7f0600ca;
        public static final int account_delete_dlg_title=0x7f0600c9;
        public static final int account_settings_action=0x7f06001b;
        public static final int account_settings_add_account_label=0x7f0600b9;
        public static final int account_settings_always_bcc_label=0x7f0600c3;
        public static final int account_settings_always_bcc_summary=0x7f0600c4;
        public static final int account_settings_composition_label=0x7f0600c2;
        public static final int account_settings_composition_title=0x7f0600c1;
        public static final int account_settings_default=0x7f0600ad;
        public static final int account_settings_default_label=0x7f0600ae;
        public static final int account_settings_default_summary=0x7f0600af;
        public static final int account_settings_description_label=0x7f0600ba;
        public static final int account_settings_email_label=0x7f0600b1;
        public static final int account_settings_incoming_label=0x7f0600b5;
        public static final int account_settings_incoming_summary=0x7f0600b6;
        public static final int account_settings_mail_check_frequency_label=0x7f0600b4;
        public static final int account_settings_name_label=0x7f0600bb;
        public static final int account_settings_notifications=0x7f0600bc;
        public static final int account_settings_notify_label=0x7f0600b0;
        public static final int account_settings_notify_summary=0x7f0600b2;
        public static final int account_settings_outgoing_label=0x7f0600b7;
        public static final int account_settings_outgoing_summary=0x7f0600b8;
        public static final int account_settings_ringtone=0x7f0600bf;
        public static final int account_settings_sent_items_label=0x7f0600c7;
        public static final int account_settings_sent_items_summary=0x7f0600c8;
        public static final int account_settings_servers=0x7f0600c0;
        public static final int account_settings_show_combined_label=0x7f0600b3;
        public static final int account_settings_signature_label=0x7f0600c5;
        public static final int account_settings_signature_summary=0x7f0600c6;
        public static final int account_settings_title_fmt=0x7f0600ac;
        public static final int account_settings_vibrate_enable=0x7f0600bd;
        public static final int account_settings_vibrate_summary=0x7f0600be;
        public static final int account_setup_account_type_imap_action=0x7f060079;
        public static final int account_setup_account_type_instructions=0x7f060077;
        public static final int account_setup_account_type_pop_action=0x7f060078;
        public static final int account_setup_account_type_title=0x7f060076;
        public static final int account_setup_account_type_webdav_action=0x7f06007a;
        public static final int account_setup_basics_default_label=0x7f060069;
        public static final int account_setup_basics_email_error_duplicate_fmt=0x7f060067;
        public static final int account_setup_basics_email_error_invalid_fmt=0x7f060066;
        public static final int account_setup_basics_email_hint=0x7f060065;
        public static final int account_setup_basics_instructions=0x7f060063;
        public static final int account_setup_basics_instructions2_fmt=0x7f060064;
        public static final int account_setup_basics_manual_setup_action=0x7f06006a;
        public static final int account_setup_basics_password_hint=0x7f060068;
        public static final int account_setup_basics_title=0x7f060062;
        public static final int account_setup_check_settings_canceling_msg=0x7f060070;
        public static final int account_setup_check_settings_check_incoming_msg=0x7f06006d;
        public static final int account_setup_check_settings_check_outgoing_msg=0x7f06006e;
        public static final int account_setup_check_settings_finishing_msg=0x7f06006f;
        public static final int account_setup_check_settings_retr_info_msg=0x7f06006c;
        public static final int account_setup_check_settings_title=0x7f06006b;
        public static final int account_setup_failed_dlg_auth_message_fmt=0x7f0600ad;
        /**  Username or password incorrect\n(ERR01 Account does not exist) 
         */
        public static final int account_setup_failed_dlg_certificate_message_fmt=0x7f0600ae;
        /**  Cannot connect to server\n(Connection timed out) 
         */
        public static final int account_setup_failed_dlg_edit_details_action=0x7f0600b0;
        public static final int account_setup_failed_dlg_invalid_certificate_accept=0x7f0600d1;
        public static final int account_setup_failed_dlg_invalid_certificate_reject=0x7f0600d2;
        public static final int account_setup_failed_dlg_invalid_certificate_title=0x7f0600d0;
        public static final int account_setup_failed_dlg_invalid_certificate_accept=0x7f0600ce;
        public static final int account_setup_failed_dlg_invalid_certificate_reject=0x7f0600cf;
        public static final int account_setup_failed_dlg_invalid_certificate_title=0x7f0600cd;
        /**  Cannot safely connect to server\n(Invalid certificate) 
         */
        public static final int account_setup_failed_dlg_server_message_fmt=0x7f0600af;
        public static final int account_setup_failed_dlg_title=0x7f0600ac;
        public static final int account_setup_finished_toast=0x7f060075;
        public static final int account_setup_incoming_delete_policy_7days_label=0x7f06008a;
        public static final int account_setup_incoming_delete_policy_delete_label=0x7f06008b;
        public static final int account_setup_incoming_delete_policy_label=0x7f060088;
        public static final int account_setup_incoming_delete_policy_never_label=0x7f060089;
        public static final int account_setup_incoming_imap_path_prefix_hint=0x7f06008d;
        public static final int account_setup_incoming_imap_path_prefix_label=0x7f06008c;
        public static final int account_setup_incoming_imap_server_label=0x7f06007f;
        public static final int account_setup_incoming_password_label=0x7f06007d;
        public static final int account_setup_incoming_pop_server_label=0x7f06007e;
        public static final int account_setup_incoming_port_label=0x7f060081;
        public static final int account_setup_incoming_security_label=0x7f060082;
        public static final int account_setup_incoming_security_none_label=0x7f060083;
        public static final int account_setup_incoming_security_ssl_label=0x7f060085;
        public static final int account_setup_incoming_security_ssl_optional_label=0x7f060084;
        public static final int account_setup_incoming_security_tls_label=0x7f060087;
        public static final int account_setup_incoming_security_tls_optional_label=0x7f060086;
        public static final int account_setup_incoming_title=0x7f06007b;
        public static final int account_setup_incoming_username_label=0x7f06007c;
        public static final int account_setup_incoming_webdav_path_prefix_hint=0x7f06008f;
        public static final int account_setup_incoming_webdav_path_prefix_label=0x7f06008e;
        public static final int account_setup_incoming_webdav_server_label=0x7f060080;
        public static final int account_setup_names_account_name_label=0x7f060073;
        public static final int account_setup_names_instructions=0x7f060072;
        public static final int account_setup_names_title=0x7f060071;
        public static final int account_setup_names_user_name_label=0x7f060074;
        public static final int account_setup_options_default_label=0x7f0600aa;
        public static final int account_setup_options_mail_check_frequency_10min=0x7f0600a6;
        public static final int account_setup_options_mail_check_frequency_15min=0x7f0600a7;
        public static final int account_setup_options_mail_check_frequency_1hour=0x7f0600a9;
        public static final int account_setup_options_mail_check_frequency_30min=0x7f0600a8;
        public static final int account_setup_options_mail_check_frequency_5min=0x7f0600a5;
        public static final int account_setup_options_mail_check_frequency_label=0x7f0600a3;
        /**  Frequency also used in account_settings_* 
         */
        public static final int account_setup_options_mail_check_frequency_never=0x7f0600a4;
        public static final int account_setup_options_notify_label=0x7f0600ab;
        public static final int account_setup_options_title=0x7f0600a2;
        public static final int account_setup_outgoing_authentication_basic_label=0x7f06009c;
        public static final int account_setup_outgoing_authentication_basic_password_label=0x7f06009e;
        public static final int account_setup_outgoing_authentication_basic_username_label=0x7f06009d;
        public static final int account_setup_outgoing_authentication_imap_before_smtp_label=0x7f0600a0;
        /**  The authentication strings below are for a planned (hopefully) change to the above username and password options 
         */
        public static final int account_setup_outgoing_authentication_label=0x7f06009b;
        public static final int account_setup_outgoing_authentication_pop_before_smtp_label=0x7f06009f;
        public static final int account_setup_outgoing_authentication_webdav_before_smtp_label=0x7f0600a1;
        public static final int account_setup_outgoing_password_label=0x7f06009a;
        public static final int account_setup_outgoing_port_label=0x7f060092;
        public static final int account_setup_outgoing_require_login_label=0x7f060098;
        public static final int account_setup_outgoing_security_label=0x7f060093;
        public static final int account_setup_outgoing_security_none_label=0x7f060094;
        public static final int account_setup_outgoing_security_ssl_label=0x7f060095;
        public static final int account_setup_outgoing_security_tls_label=0x7f060097;
        public static final int account_setup_outgoing_security_tls_optional_label=0x7f060096;
        public static final int account_setup_outgoing_smtp_server_label=0x7f060091;
        public static final int account_setup_outgoing_title=0x7f060090;
        public static final int account_setup_outgoing_username_label=0x7f060099;
        public static final int accounts_action=0x7f06001d;
        public static final int accounts_context_menu_title=0x7f060029;
        public static final int accounts_title=0x7f060004;
        public static final int accounts_welcome=0x7f06003b;
        public static final int add_account_action=0x7f060016;
        public static final int add_attachment_action=0x7f060026;
        public static final int add_cc_bcc_action=0x7f060024;
        public static final int app_name=0x7f060001;
        public static final int build_number=0x7f060000;
        /**   User to confirm acceptance of dialog boxes, warnings, errors, etc. 
         */
        public static final int cancel_action=0x7f060009;
        public static final int combined_inbox_label=0x7f060041;
        public static final int combined_inbox_list_title=0x7f060042;
        public static final int combined_inbox_title=0x7f060040;
        public static final int compose_action=0x7f060017;
        public static final int compose_title=0x7f060005;
        public static final int continue_action=0x7f06000f;
        public static final int debug_enable_debug_logging_label=0x7f06003d;
        public static final int debug_enable_sensitive_logging_label=0x7f06003e;
        public static final int debug_title=0x7f060006;
        public static final int debug_version_fmt=0x7f06003c;
        public static final int delete_action=0x7f06000d;
        public static final int discard_action=0x7f060012;
        public static final int done_action=0x7f060010;
        public static final int dump_settings_action=0x7f060027;
        public static final int edit_subject_action=0x7f060025;
        public static final int empty_trash_action=0x7f060028;
        public static final int folders_action=0x7f060022;
        public static final int forward_action=0x7f06000e;
        public static final int general_no_subject=0x7f06002a;
        public static final int mailbox_select_dlg_new_mailbox_action=0x7f06005b;
        public static final int mailbox_select_dlg_title=0x7f06005a;
        public static final int mark_as_read_action=0x7f06001f;
        public static final int mark_as_unread_action=0x7f060020;
        public static final int message_compose_attachments_skipped_toast=0x7f06004e;
        public static final int message_compose_bcc_hint=0x7f060047;
        public static final int message_compose_cc_hint=0x7f060046;
        public static final int message_compose_downloading_attachments_toast=0x7f06004d;
        public static final int message_compose_error_no_recipients=0x7f06004c;
        public static final int message_compose_fwd_header_fmt=0x7f060049;
        public static final int message_compose_quoted_text_label=0x7f06004b;
        public static final int message_compose_reply_header_fmt=0x7f06004a;
        public static final int message_compose_subject_hint=0x7f060048;
        public static final int message_compose_to_hint=0x7f060045;
        public static final int message_copied_toast=0x7f06005d;
        public static final int message_deleted_toast=0x7f06005f;
        public static final int message_discarded_toast=0x7f060060;
        public static final int message_header_mua=0x7f06003f;
        /**  Inbox (12) 
         */
        public static final int message_list_load_more_messages_action=0x7f060044;
        /**  Inbox here should be the same as mailbox_name_inbox 
         */
        public static final int message_list_title_fmt=0x7f060043;
        public static final int message_moved_toast=0x7f06005e;
        public static final int message_saved_toast=0x7f060061;
        public static final int message_view_attachment_download_action=0x7f060051;
        public static final int message_view_attachment_view_action=0x7f060050;
        public static final int message_view_datetime_fmt=0x7f060054;
        public static final int message_view_fetching_attachment_toast=0x7f060059;
        public static final int message_view_next_action=0x7f060053;
        public static final int message_view_prev_action=0x7f060052;
        public static final int message_view_show_pictures_action=0x7f060058;
        public static final int message_view_show_pictures_instructions=0x7f060057;
        public static final int message_view_status_attachment_not_saved=0x7f060056;
        public static final int message_view_status_attachment_saved=0x7f060055;
        public static final int message_view_to_label=0x7f06004f;
        public static final int move_to_action=0x7f060021;
        public static final int new_mailbox_dlg_title=0x7f06005c;
        /**  Actions will be used as buttons and in menu items 
         */
        public static final int next_action=0x7f060007;
        /**  279 Unread (someone@google.com) 
         */
        public static final int notification_new_multi_account_fmt=0x7f060034;
        public static final int notification_new_one_account_fmt=0x7f060033;
        public static final int notification_new_scrolling=0x7f060032;
        public static final int notification_new_title=0x7f060031;
        public static final int notification_unsent_title=0x7f060035;
        /**  Used as part of a multi-step process 
         */
        public static final int okay_action=0x7f060008;
        public static final int open_action=0x7f06001a;
        public static final int preferences_action=0x7f060019;
        public static final int provider_note_live=0x7f0600cc;
        public static final int provider_note_yahoo=0x7f0600cb;
        public static final int read_action=0x7f06001e;
        public static final int read_attachment_desc=0x7f060003;
        public static final int read_attachment_label=0x7f060002;
        public static final int refresh_action=0x7f060015;
        public static final int remove_account_action=0x7f06001c;
        /**   Used to complete a multi-step process 
         */
        public static final int remove_action=0x7f060011;
        public static final int reply_action=0x7f06000b;
        public static final int reply_all_action=0x7f06000c;
        public static final int retry_action=0x7f060014;
        public static final int save_draft_action=0x7f060013;
        public static final int search_action=0x7f060018;
        public static final int send_action=0x7f06000a;
        /**  The following mailbox names will be used if the user has not specified one from the server 
         */
        public static final int special_mailbox_name_drafts=0x7f060038;
        public static final int special_mailbox_name_inbox=0x7f060036;
        public static final int special_mailbox_name_outbox=0x7f060037;
        public static final int special_mailbox_name_sent=0x7f06003a;
        public static final int special_mailbox_name_trash=0x7f060039;
        public static final int status_error=0x7f06002e;
        /**  Shown in place of the subject when a message has no subject. Showing this in parentheses is customary. 
         */
        public static final int status_loading=0x7f06002b;
        public static final int status_loading_more=0x7f06002c;
        /**  Used in Outbox when a message is currently sending 
         */
        public static final int status_loading_more_failed=0x7f060030;
        public static final int status_network_error=0x7f06002d;
        /**  Used in Outbox when a message has failed to send 
         */
        public static final int status_sending=0x7f06002f;
        public static final int view_hide_details_action=0x7f060023;
    }
    public static final class xml {
        public static final int account_settings_preferences=0x7f040000;
        public static final int providers=0x7f040001;
    }
}
