/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.fsck.k9;

public final class Manifest {
    public static final class permission {
        public static final String READ_ATTACHMENT="com.fsck.k9.permission.READ_ATTACHMENT";
    }
}
