/* Generated By:JavaCC: Do not edit this line. StructuredFieldParserConstants.java */
/****************************************************************
 * Licensed to the Apache Software Foundation (ASF) under one   *
 * or more contributor license agreements.  See the NOTICE file *
 * distributed with this work for additional information        *
 * regarding copyright ownership.  The ASF licenses this file   *
 * to you under the Apache License, Version 2.0 (the            *
 * "License"); you may not use this file except in compliance   *
 * with the License.  You may obtain a copy of the License at   *
 *                                                              *
 *   http://www.apache.org/licenses/LICENSE-2.0                 *
 *                                                              *
 * Unless required by applicable law or agreed to in writing,   *
 * software distributed under the License is distributed on an  *
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY       *
 * KIND, either express or implied.  See the License for the    *
 * specific language governing permissions and limitations      *
 * under the License.                                           *
 ****************************************************************/
package org.apache.james.mime4j.field.structured.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface StructuredFieldParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STRING_CONTENT = 11;
  /** RegularExpression Id. */
  int FOLD = 12;
  /** RegularExpression Id. */
  int QUOTEDSTRING = 13;
  /** RegularExpression Id. */
  int WS = 14;
  /** RegularExpression Id. */
  int CONTENT = 15;
  /** RegularExpression Id. */
  int QUOTEDPAIR = 16;
  /** RegularExpression Id. */
  int ANY = 17;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int INCOMMENT = 1;
  /** Lexical state. */
  int NESTED_COMMENT = 2;
  /** Lexical state. */
  int INQUOTEDSTRING = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\")\"",
    "\"(\"",
    "<token of kind 4>",
    "\"(\"",
    "\")\"",
    "<token of kind 7>",
    "<token of kind 8>",
    "\"\\\"\"",
    "<token of kind 10>",
    "<STRING_CONTENT>",
    "<FOLD>",
    "\"\\\"\"",
    "<WS>",
    "<CONTENT>",
    "<QUOTEDPAIR>",
    "<ANY>",
  };

}
