package net.thunderbird.core.ui.compose.designsystem.atom.icon.outlined

import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.tooling.preview.Preview
import net.thunderbird.core.ui.compose.designsystem.atom.icon.Icon
import net.thunderbird.core.ui.compose.designsystem.atom.icon.icon
import net.thunderbird.core.ui.compose.designsystem.atom.icon.iconPath

internal val OutlinedQrCode: ImageVector by lazy {
    icon(name = "OutlinedQrCode", viewportWidth = 18f, viewportHeight = 18f) {
        iconPath {
            moveTo(x = 2.25f, y = 8.25f)
            verticalLineTo(y = 2.25f)
            horizontalLineTo(x = 8.25f)
            verticalLineTo(y = 8.25f)
            horizontalLineTo(x = 2.25f)
            close()
            moveTo(x = 3.75f, y = 6.75f)
            horizontalLineTo(x = 6.75f)
            verticalLineTo(y = 3.75f)
            horizontalLineTo(x = 3.75f)
            verticalLineTo(y = 6.75f)
            close()
            moveTo(x = 2.25f, y = 15.75f)
            verticalLineTo(y = 9.75f)
            horizontalLineTo(x = 8.25f)
            verticalLineTo(y = 15.75f)
            horizontalLineTo(x = 2.25f)
            close()
            moveTo(x = 3.75f, y = 14.25f)
            horizontalLineTo(x = 6.75f)
            verticalLineTo(y = 11.25f)
            horizontalLineTo(x = 3.75f)
            verticalLineTo(y = 14.25f)
            close()
            moveTo(x = 9.75f, y = 8.25f)
            verticalLineTo(y = 2.25f)
            horizontalLineTo(x = 15.75f)
            verticalLineTo(y = 8.25f)
            horizontalLineTo(x = 9.75f)
            close()
            moveTo(x = 11.25f, y = 6.75f)
            horizontalLineTo(x = 14.25f)
            verticalLineTo(y = 3.75f)
            horizontalLineTo(x = 11.25f)
            verticalLineTo(y = 6.75f)
            close()
            moveTo(x = 14.25f, y = 15.75f)
            verticalLineTo(y = 14.25f)
            horizontalLineTo(x = 15.75f)
            verticalLineTo(y = 15.75f)
            horizontalLineTo(x = 14.25f)
            close()
            moveTo(x = 9.75f, y = 11.25f)
            verticalLineTo(y = 9.75f)
            horizontalLineTo(x = 11.25f)
            verticalLineTo(y = 11.25f)
            horizontalLineTo(x = 9.75f)
            close()
            moveTo(x = 11.25f, y = 12.75f)
            verticalLineTo(y = 11.25f)
            horizontalLineTo(x = 12.75f)
            verticalLineTo(y = 12.75f)
            horizontalLineTo(x = 11.25f)
            close()
            moveTo(x = 9.75f, y = 14.25f)
            verticalLineTo(y = 12.75f)
            horizontalLineTo(x = 11.25f)
            verticalLineTo(y = 14.25f)
            horizontalLineTo(x = 9.75f)
            close()
            moveTo(x = 11.25f, y = 15.75f)
            verticalLineTo(y = 14.25f)
            horizontalLineTo(x = 12.75f)
            verticalLineTo(y = 15.75f)
            horizontalLineTo(x = 11.25f)
            close()
            moveTo(x = 12.75f, y = 14.25f)
            verticalLineTo(y = 12.75f)
            horizontalLineTo(x = 14.25f)
            verticalLineTo(y = 14.25f)
            horizontalLineTo(x = 12.75f)
            close()
            moveTo(x = 12.75f, y = 11.25f)
            verticalLineTo(y = 9.75f)
            horizontalLineTo(x = 14.25f)
            verticalLineTo(y = 11.25f)
            horizontalLineTo(x = 12.75f)
            close()
            moveTo(x = 14.25f, y = 12.75f)
            verticalLineTo(y = 11.25f)
            horizontalLineTo(x = 15.75f)
            verticalLineTo(y = 12.75f)
            horizontalLineTo(x = 14.25f)
            close()
        }
    }
}

@Preview(name = "QrCode", showBackground = true)
@Composable
private fun QrCodePreview() {
    Icon(imageVector = OutlinedQrCode)
}
