---
name: Build - Scripts

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/**'
      - '.github/workflows/build-scripts.yml'
  pull_request:
    paths:
      - 'scripts/**'
      - '.github/workflows/build-scripts.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-scripts:
    name: Build scripts
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout the repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # @v6.3.0
        with:
          python-version: '3.14'

      - name: Run Python script tests
        run: bash scripts/test_python_scripts.sh
