---
name: Issue - Remove answered label

on:
  issues:
    types:
      - labeled

permissions:
  issues: write

jobs:
  issue-needinfo-answered:
    name: Remove 'answered' label when both exist
    runs-on: ubuntu-latest
    if: |
      contains(github.event.issue.labels.*.name, 'status: needs information') &&
      contains(github.event.issue.labels.*.name, 'status: answered')
    environment: botmobile
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: App token generate
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3  # v3.1.1
        if: ${{ vars.BOT_CLIENT_ID }}
        id: app-token
        with:
          client-id: ${{ vars.BOT_CLIENT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Remove answered label if both exist
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GH_TOKEN: ${{ steps.app-token.outputs.token || github.token }}
        run: |
          gh issue edit $ISSUE_NUMBER --repo "$GITHUB_REPOSITORY" --remove-label "status: answered"
