---
name: Close old issues with the needinfo label

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: botmobile
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: App token generate
        uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b  # v2.1.1
        if: ${{ vars.BOT_CLIENT_ID }}
        id: app-token
        with:
          app-id: ${{ vars.BOT_CLIENT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Close old issues with the needinfo tag
        uses: imhoffd/needs-reply@71e8d5144caa0d4a1e292348bfafa3866d08c855  # v2.0.0
        with:
          repo-token: ${{ steps.app-token.outputs.token || github.token }}
          issue-label: "status: needs information"
          days-before-close: 30
          close-message: >
            Thank you for taking the time to report this issue. It looks like we haven't heard back
            in a while, therefore we're closing this issue. If the problem persists in the latest
            version please open a new issue and reference this one so we can follow up more
            effectively.
