name: Quality checks

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'

concurrency:
  group: quality-checks-${{ github.ref }}-${{ github.event.pull_request.number || 'no-pr' }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  quality-spotless:
    name: Spotless check
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 1

      - name: Setup Gradle environment
        uses: ./.github/actions/setup-gradle

      - name: Quality - Spotless
        run: ./gradlew spotlessCheck

  quality-detekt:
    name: Detekt check
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 1

      - name: Setup Gradle environment
        uses: ./.github/actions/setup-gradle

      - name: Quality - Detekt
        run: ./gradlew detekt

      - name: Running Detekt including KMP
        # As we were not verifying detekt in KMP sources before,
        # this step is likely to fail.
        continue-on-error: true
        run: |
          ./gradlew detektMetadataCommonMain
          ./gradlew detektMetadataMain
          ./gradlew detektMetadataCommonJvmMain

  quality-dependency-guard:
    name: Dependency guard check
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 1

      - name: Setup Gradle environment
        uses: ./.github/actions/setup-gradle

      - name: Quality - Dependency guard
        run: ./gradlew dependencyGuard

  quality-konsist:
    name: Konsist check
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 1

      - name: Setup Gradle environment
        uses: ./.github/actions/setup-gradle

      - name: Quality - Konsist
        run: ./gradlew :quality:konsist:test
