---
name: Validate - Gradle Wrapper

on:
  pull_request:

permissions:
  contents: read

jobs:
  validate-gradle:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: gradle/actions/wrapper-validation@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2
